### ISSUE TITLE
"Invalid Memory Read at Address" Error

### ISSUE THREAD

**Issue by Wardrop** [meh/ruby-tesseract-ocr#12]
I consistently get a FFI::NullPointerError when using Tesseract-OCR and elements.

```
require 'tesseract-ocr'

image_path = ARGV[0]
engine = Tesseract::Engine.new
engine.page_segmentation_mode = :AUTO
engine.image = image_path
engine.blocks # Error occurs here
```

The error (with backtrace) is always:

```
../.rvm/gems/ruby-1.9.3-p327/gems/ffi-1.2.0/lib/ffi/pointer.rb:42:in `get_string': invalid memory read at address=0x00000000000000 (FFI::NullPointerError)
from ../.rvm/gems/ruby-1.9.3-p327/gems/ffi-1.2.0/lib/ffi/pointer.rb:42:in `read_string'
from ../.rvm/gems/ruby-1.9.3-p327/gems/tesseract-ocr-0.1.5/lib/tesseract/api/iterator.rb:78:in `get_text'
from ../.rvm/gems/ruby-1.9.3-p327/gems/tesseract-ocr-0.1.5/lib/tesseract/engine/iterator.rb:72:in `text'
from ../.rvm/gems/ruby-1.9.3-p327/gems/call-me-0.0.2.3/lib/call-me/memoize.rb:44:in `block in memoize'
from ../.rvm/gems/ruby-1.9.3-p327/gems/tesseract-ocr-0.1.5/lib/tesseract/engine/iterator.rb:147:in `block (4 levels) in <class:Iterator>'
from ../.rvm/gems/ruby-1.9.3-p327/gems/tesseract-ocr-0.1.5/lib/tesseract/engine/iterator.rb:145:in `each'
from ../.rvm/gems/ruby-1.9.3-p327/gems/tesseract-ocr-0.1.5/lib/tesseract/engine/iterator.rb:145:in `block (3 levels) in <class:Iterator>'
from ../.rvm/gems/ruby-1.9.3-p327/gems/tesseract-ocr-0.1.5/lib/tesseract/engine/iterator.rb:139:in `call'
from ../.rvm/gems/ruby-1.9.3-p327/gems/tesseract-ocr-0.1.5/lib/tesseract/engine/iterator.rb:139:in `block (2 levels) in <class:Iterator>'
from ../.rvm/gems/ruby-1.9.3-p327/gems/tesseract-ocr-0.1.5/lib/tesseract/engine/iterator.rb:144:in `each'
from ../.rvm/gems/ruby-1.9.3-p327/gems/tesseract-ocr-0.1.5/lib/tesseract/engine/iterator.rb:144:in `map'
from ../.rvm/gems/ruby-1.9.3-p327/gems/tesseract-ocr-0.1.5/lib/tesseract/engine/iterator.rb:144:in `block (2 levels) in <class:Iterator>'
from ../.rvm/gems/ruby-1.9.3-p327/gems/tesseract-ocr-0.1.5/lib/tesseract/engine.rb:199:in `block (2 levels) in <class:Engine>'
from test.rb:7:in `<main>'
```

I'm on OS X. It's seems so common that I'm either missing something fundamental in the above code, or OS X is simply an unsupported platform?

**Comment by sushil10018** [comment]
Is this issue fixed? 
below is the error msg seen while trying to execute text_for
```ruby
extracted_text = e.text_for(img).strip
Error in pixcmapToArrays: calloc fail for *map
Error in pixRemoveColormap: colormap arrays not made
Error in pixGetDepth: pix not defined
Error in pixGetWpl: pix not defined
Please call SetImage before attempting recognition.Please call SetImage before attempting recognition.FFI::NullPointerError: invalid memory read at address=0x00000000000000
```

Though, tesseract works directly through bash. What could be the possible misconfiguration?

Thanks in advance.

**Comment by meh** [comment]
@sushil10018 do you have a full backtrace of the error?
