### ISSUE TITLE
CompliationError

### ISSUE THREAD

**Issue by kiwiwin** [meh/ruby-tesseract-ocr#18]
```
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/ffi-inline-0.0.4.3/lib/ffi/inline/compilers/gcc.rb:35:in `compile': compile error: see logs at /tmp/.ffi-inline-1000/a8cf93ed3dd2ddcfa6919b6e0decd89a36a9dd30.log (CompilationError)
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/ffi-inline-0.0.4.3/lib/ffi/inline/builders/c.rb:114:in `shared_object'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/ffi-inline-0.0.4.3/lib/ffi/inline/builders.rb:90:in `block in build'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/ffi-inline-0.0.4.3/lib/ffi/inline/builders.rb:87:in `instance_eval'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/ffi-inline-0.0.4.3/lib/ffi/inline/builders.rb:87:in `build'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/ffi-inline-0.0.4.3/lib/ffi/inline/inline.rb:54:in `singleton_inline'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/ffi-inline-0.0.4.3/lib/ffi/inline/inline.rb:39:in `inline'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/tesseract-ocr-0.1.5/lib/tesseract/c.rb:34:in `<module:C>'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/tesseract-ocr-0.1.5/lib/tesseract/c.rb:31:in `<module:Tesseract>'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/tesseract-ocr-0.1.5/lib/tesseract/c.rb:29:in `<top (required)>'
    from /usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/tesseract-ocr-0.1.5/lib/tesseract/api.rb:26:in `<top (required)>'
    from /usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/tesseract-ocr-0.1.5/lib/tesseract-ocr.rb:35:in `<top (required)>'
    from /usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/tesseract-ocr-0.1.5/lib/tesseract.rb:25:in `<top (required)>'
    from /usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
    from /usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
    from /usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from test.rb:1:in `<main>'
```

**Comment by mntj** [comment]
@leoromanovsky I was able to fix by installing `libleptonica-dev` and `libtesseract-dev`
